---

- name: brew cask software
  community.general.homebrew_cask:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - alfred
      - github
      - whatsapp
      - 1password-cli
      - iterm2
      - alacritty
      - notion
      - google-chrome
      - visual-studio-code
      - orbstack

- name: brew packages
  community.general.homebrew:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - ansible
      - mise
      - powerlevel9k
      - fzf
      - gh
      - neovim
      - neofetch
      - nmap
      - ranger
      - ripgrep
      - speedtest
      - stow
      - tmux
